fix: Disable xtables-addons to support rpi kernel
Alpine's rpi kernel flavor doesn't have xtables-addons-rpi package.
Set kernel_addons="" to prevent automatic installation.

This fixes the build error:
ERROR: unable to select packages:
  xtables-addons-rpi (no such package)